/* Automatically generated by parse_images.py */
const PARASITE_IMAGES = [
    {
        "filename": "Ancylostoma caninum adult.jpg",
        "filepath": "pictures/Ancylostoma caninum adult.jpg",
        "parasiteName": "Ancylostoma caninum",
        "genus": "Ancylostoma",
        "species": "caninum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Ancylostoma caninum adult2.jpg",
        "filepath": "pictures/Ancylostoma caninum adult2.jpg",
        "parasiteName": "Ancylostoma caninum",
        "genus": "Ancylostoma",
        "species": "caninum",
        "stage": "adult2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Ancylostoma caninum adult3.jpg",
        "filepath": "pictures/Ancylostoma caninum adult3.jpg",
        "parasiteName": "Ancylostoma caninum",
        "genus": "Ancylostoma",
        "species": "caninum",
        "stage": "adult3",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Ancylostoma caninum egg.jpg",
        "filepath": "pictures/Ancylostoma caninum egg.jpg",
        "parasiteName": "Ancylostoma caninum",
        "genus": "Ancylostoma",
        "species": "caninum",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Ancylostoma caninum larva.jpg",
        "filepath": "pictures/Ancylostoma caninum larva.jpg",
        "parasiteName": "Ancylostoma caninum",
        "genus": "Ancylostoma",
        "species": "caninum",
        "stage": "larva",
        "stageClean": "Larva/Microfilaria (幼蟲/微絲蚴)",
        "isLifecycle": false
    },
    {
        "filename": "Ancylostoma caninum life cycle.jpg",
        "filepath": "pictures/Ancylostoma caninum life cycle.jpg",
        "parasiteName": "Ancylostoma caninum",
        "genus": "Ancylostoma",
        "species": "caninum",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Ancylostoma ceylanicum adult.jpg",
        "filepath": "pictures/Ancylostoma ceylanicum adult.jpg",
        "parasiteName": "Ancylostoma ceylanicum",
        "genus": "Ancylostoma",
        "species": "ceylanicum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Ancylostoma duodenale adult.jpg",
        "filepath": "pictures/Ancylostoma duodenale adult.jpg",
        "parasiteName": "Ancylostoma duodenale",
        "genus": "Ancylostoma",
        "species": "duodenale",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Ancylostoma duodenale egg.jpg",
        "filepath": "pictures/Ancylostoma duodenale egg.jpg",
        "parasiteName": "Ancylostoma duodenale",
        "genus": "Ancylostoma",
        "species": "duodenale",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Angiostrongylus cantonensis adult.jpg",
        "filepath": "pictures/Angiostrongylus cantonensis adult.jpg",
        "parasiteName": "Angiostrongylus cantonensis",
        "genus": "Angiostrongylus",
        "species": "cantonensis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Angiostrongylus cantonensis egg.jpg",
        "filepath": "pictures/Angiostrongylus cantonensis egg.jpg",
        "parasiteName": "Angiostrongylus cantonensis",
        "genus": "Angiostrongylus",
        "species": "cantonensis",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Angiostrongylus cantonensis L3.jpg",
        "filepath": "pictures/Angiostrongylus cantonensis L3.jpg",
        "parasiteName": "Angiostrongylus cantonensis",
        "genus": "Angiostrongylus",
        "species": "cantonensis",
        "stage": "L3",
        "stageClean": "Larva/Microfilaria (幼蟲/微絲蚴)",
        "isLifecycle": false
    },
    {
        "filename": "Angiostrongylus cantonensis life cycle.jpg",
        "filepath": "pictures/Angiostrongylus cantonensis life cycle.jpg",
        "parasiteName": "Angiostrongylus cantonensis",
        "genus": "Angiostrongylus",
        "species": "cantonensis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Ascaris lumbricoides adult.jpg",
        "filepath": "pictures/Ascaris lumbricoides adult.jpg",
        "parasiteName": "Ascaris lumbricoides",
        "genus": "Ascaris",
        "species": "lumbricoides",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Ascaris lumbricoides egg.jpg",
        "filepath": "pictures/Ascaris lumbricoides egg.jpg",
        "parasiteName": "Ascaris lumbricoides",
        "genus": "Ascaris",
        "species": "lumbricoides",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Ascaris lumbricoides life cycle.jpg",
        "filepath": "pictures/Ascaris lumbricoides life cycle.jpg",
        "parasiteName": "Ascaris lumbricoides",
        "genus": "Ascaris",
        "species": "lumbricoides",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Balantidium coli 2.jpg",
        "filepath": "pictures/Balantidium coli 2.jpg",
        "parasiteName": "Balantidium coli",
        "genus": "Balantidium",
        "species": "coli",
        "stage": "2",
        "stageClean": "2",
        "isLifecycle": false
    },
    {
        "filename": "Balantidium coli 3.jpg",
        "filepath": "pictures/Balantidium coli 3.jpg",
        "parasiteName": "Balantidium coli",
        "genus": "Balantidium",
        "species": "coli",
        "stage": "3",
        "stageClean": "3",
        "isLifecycle": false
    },
    {
        "filename": "Balantidium coli life cycle.jpg",
        "filepath": "pictures/Balantidium coli life cycle.jpg",
        "parasiteName": "Balantidium coli",
        "genus": "Balantidium",
        "species": "coli",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Balantidium coli.jpg",
        "filepath": "pictures/Balantidium coli.jpg",
        "parasiteName": "Balantidium coli",
        "genus": "Balantidium",
        "species": "coli",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Brugia malayi L3.jpg",
        "filepath": "pictures/Brugia malayi L3.jpg",
        "parasiteName": "Brugia malayi",
        "genus": "Brugia",
        "species": "malayi",
        "stage": "L3",
        "stageClean": "Larva/Microfilaria (幼蟲/微絲蚴)",
        "isLifecycle": false
    },
    {
        "filename": "Brugia malayi life cycle.jpg",
        "filepath": "pictures/Brugia malayi life cycle.jpg",
        "parasiteName": "Brugia malayi",
        "genus": "Brugia",
        "species": "malayi",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Brugia malayi MICROFILARIA.jpg",
        "filepath": "pictures/Brugia malayi MICROFILARIA.jpg",
        "parasiteName": "Brugia malayi",
        "genus": "Brugia",
        "species": "malayi",
        "stage": "MICROFILARIA",
        "stageClean": "Larva/Microfilaria (幼蟲/微絲蚴)",
        "isLifecycle": false
    },
    {
        "filename": "Capillaria philippinensis adult.jpg",
        "filepath": "pictures/Capillaria philippinensis adult.jpg",
        "parasiteName": "Capillaria philippinensis",
        "genus": "Capillaria",
        "species": "philippinensis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Capillaria philippinensis egg.jpg",
        "filepath": "pictures/Capillaria philippinensis egg.jpg",
        "parasiteName": "Capillaria philippinensis",
        "genus": "Capillaria",
        "species": "philippinensis",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Capillaria philippinensis life cycle.jpg",
        "filepath": "pictures/Capillaria philippinensis life cycle.jpg",
        "parasiteName": "Capillaria philippinensis",
        "genus": "Capillaria",
        "species": "philippinensis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Clonorchis sinensis adult.jpg",
        "filepath": "pictures/Clonorchis sinensis adult.jpg",
        "parasiteName": "Clonorchis sinensis",
        "genus": "Clonorchis",
        "species": "sinensis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Clonorchis sinensis egg 2.jpg",
        "filepath": "pictures/Clonorchis sinensis egg 2.jpg",
        "parasiteName": "Clonorchis sinensis",
        "genus": "Clonorchis",
        "species": "sinensis",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Clonorchis sinensis egg 3.jpg",
        "filepath": "pictures/Clonorchis sinensis egg 3.jpg",
        "parasiteName": "Clonorchis sinensis",
        "genus": "Clonorchis",
        "species": "sinensis",
        "stage": "egg 3",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Clonorchis sinensis egg.jpg",
        "filepath": "pictures/Clonorchis sinensis egg.jpg",
        "parasiteName": "Clonorchis sinensis",
        "genus": "Clonorchis",
        "species": "sinensis",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Clonorchis sinensis life cycle.jpg",
        "filepath": "pictures/Clonorchis sinensis life cycle.jpg",
        "parasiteName": "Clonorchis sinensis",
        "genus": "Clonorchis",
        "species": "sinensis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Cryptosporidium parvum life cycle.jpg",
        "filepath": "pictures/Cryptosporidium parvum life cycle.jpg",
        "parasiteName": "Cryptosporidium parvum",
        "genus": "Cryptosporidium",
        "species": "parvum",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Cryptosporidium parvum.jpg",
        "filepath": "pictures/Cryptosporidium parvum.jpg",
        "parasiteName": "Cryptosporidium parvum",
        "genus": "Cryptosporidium",
        "species": "parvum",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Dicrocoelium dendriticum adult 2.jpg",
        "filepath": "pictures/Dicrocoelium dendriticum adult 2.jpg",
        "parasiteName": "Dicrocoelium dendriticum",
        "genus": "Dicrocoelium",
        "species": "dendriticum",
        "stage": "adult 2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Dicrocoelium dendriticum adult.jpg",
        "filepath": "pictures/Dicrocoelium dendriticum adult.jpg",
        "parasiteName": "Dicrocoelium dendriticum",
        "genus": "Dicrocoelium",
        "species": "dendriticum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Dicrocoelium dendriticum egg.jpg",
        "filepath": "pictures/Dicrocoelium dendriticum egg.jpg",
        "parasiteName": "Dicrocoelium dendriticum",
        "genus": "Dicrocoelium",
        "species": "dendriticum",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Diphyllobothrium latum adult 2.jpg",
        "filepath": "pictures/Diphyllobothrium latum adult 2.jpg",
        "parasiteName": "Diphyllobothrium latum",
        "genus": "Diphyllobothrium",
        "species": "latum",
        "stage": "adult 2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Diphyllobothrium latum adult.jpg",
        "filepath": "pictures/Diphyllobothrium latum adult.jpg",
        "parasiteName": "Diphyllobothrium latum",
        "genus": "Diphyllobothrium",
        "species": "latum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Diphyllobothrium latum egg 2.jpg",
        "filepath": "pictures/Diphyllobothrium latum egg 2.jpg",
        "parasiteName": "Diphyllobothrium latum",
        "genus": "Diphyllobothrium",
        "species": "latum",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Diphyllobothrium latum egg.jpg",
        "filepath": "pictures/Diphyllobothrium latum egg.jpg",
        "parasiteName": "Diphyllobothrium latum",
        "genus": "Diphyllobothrium",
        "species": "latum",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Diphyllobothrium latum Plerocercoid.jpg",
        "filepath": "pictures/Diphyllobothrium latum Plerocercoid.jpg",
        "parasiteName": "Diphyllobothrium latum",
        "genus": "Diphyllobothrium",
        "species": "latum",
        "stage": "Plerocercoid",
        "stageClean": "Plerocercoid",
        "isLifecycle": false
    },
    {
        "filename": "Dipylidium caninum adult.jpg",
        "filepath": "pictures/Dipylidium caninum adult.jpg",
        "parasiteName": "Dipylidium caninum",
        "genus": "Dipylidium",
        "species": "caninum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Dipylidium caninum body.jpg",
        "filepath": "pictures/Dipylidium caninum body.jpg",
        "parasiteName": "Dipylidium caninum",
        "genus": "Dipylidium",
        "species": "caninum",
        "stage": "body",
        "stageClean": "body",
        "isLifecycle": false
    },
    {
        "filename": "Dipylidium caninum egg 2.jpg",
        "filepath": "pictures/Dipylidium caninum egg 2.jpg",
        "parasiteName": "Dipylidium caninum",
        "genus": "Dipylidium",
        "species": "caninum",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Dipylidium caninum egg.jpg",
        "filepath": "pictures/Dipylidium caninum egg.jpg",
        "parasiteName": "Dipylidium caninum",
        "genus": "Dipylidium",
        "species": "caninum",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Dirofilaria immitis adult.jpg",
        "filepath": "pictures/Dirofilaria immitis adult.jpg",
        "parasiteName": "Dirofilaria immitis",
        "genus": "Dirofilaria",
        "species": "immitis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Dirofilaria immitis life cycle.jpg",
        "filepath": "pictures/Dirofilaria immitis life cycle.jpg",
        "parasiteName": "Dirofilaria immitis",
        "genus": "Dirofilaria",
        "species": "immitis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Dracunculus medinensis adult.jpg",
        "filepath": "pictures/Dracunculus medinensis adult.jpg",
        "parasiteName": "Dracunculus medinensis",
        "genus": "Dracunculus",
        "species": "medinensis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Dracunculus medinensis life cycle.jpg",
        "filepath": "pictures/Dracunculus medinensis life cycle.jpg",
        "parasiteName": "Dracunculus medinensis",
        "genus": "Dracunculus",
        "species": "medinensis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Echinococcus granulosus adult.jpg",
        "filepath": "pictures/Echinococcus granulosus adult.jpg",
        "parasiteName": "Echinococcus granulosus",
        "genus": "Echinococcus",
        "species": "granulosus",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Echinostoma revolutum adult.jpg",
        "filepath": "pictures/Echinostoma revolutum adult.jpg",
        "parasiteName": "Echinostoma revolutum",
        "genus": "Echinostoma",
        "species": "revolutum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Echinostoma revolutum egg.jpg",
        "filepath": "pictures/Echinostoma revolutum egg.jpg",
        "parasiteName": "Echinostoma revolutum",
        "genus": "Echinostoma",
        "species": "revolutum",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Echinostoma revolutum egg2.jpg",
        "filepath": "pictures/Echinostoma revolutum egg2.jpg",
        "parasiteName": "Echinostoma revolutum",
        "genus": "Echinostoma",
        "species": "revolutum",
        "stage": "egg2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Entamoeba coli 2.jpg",
        "filepath": "pictures/Entamoeba coli 2.jpg",
        "parasiteName": "Entamoeba coli",
        "genus": "Entamoeba",
        "species": "coli",
        "stage": "2",
        "stageClean": "2",
        "isLifecycle": false
    },
    {
        "filename": "Entamoeba coli life cycle.jpg",
        "filepath": "pictures/Entamoeba coli life cycle.jpg",
        "parasiteName": "Entamoeba coli",
        "genus": "Entamoeba",
        "species": "coli",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Entamoeba coli.jpg",
        "filepath": "pictures/Entamoeba coli.jpg",
        "parasiteName": "Entamoeba coli",
        "genus": "Entamoeba",
        "species": "coli",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Entamoeba histolytica 2.jpg",
        "filepath": "pictures/Entamoeba histolytica 2.jpg",
        "parasiteName": "Entamoeba histolytica",
        "genus": "Entamoeba",
        "species": "histolytica",
        "stage": "2",
        "stageClean": "2",
        "isLifecycle": false
    },
    {
        "filename": "Entamoeba histolytica life cycle.jpg",
        "filepath": "pictures/Entamoeba histolytica life cycle.jpg",
        "parasiteName": "Entamoeba histolytica",
        "genus": "Entamoeba",
        "species": "histolytica",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Entamoeba histolytica.jpg",
        "filepath": "pictures/Entamoeba histolytica.jpg",
        "parasiteName": "Entamoeba histolytica",
        "genus": "Entamoeba",
        "species": "histolytica",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Enterobius vermicularis adult.jpg",
        "filepath": "pictures/Enterobius vermicularis adult.jpg",
        "parasiteName": "Enterobius vermicularis",
        "genus": "Enterobius",
        "species": "vermicularis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Enterobius vermicularis egg.jpg",
        "filepath": "pictures/Enterobius vermicularis egg.jpg",
        "parasiteName": "Enterobius vermicularis",
        "genus": "Enterobius",
        "species": "vermicularis",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Enterobius vermicularis life cycle.jpg",
        "filepath": "pictures/Enterobius vermicularis life cycle.jpg",
        "parasiteName": "Enterobius vermicularis",
        "genus": "Enterobius",
        "species": "vermicularis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Fasciola hepatica adult.jpg",
        "filepath": "pictures/Fasciola hepatica adult.jpg",
        "parasiteName": "Fasciola hepatica",
        "genus": "Fasciola",
        "species": "hepatica",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Fasciola hepatica adult2.jpg",
        "filepath": "pictures/Fasciola hepatica adult2.jpg",
        "parasiteName": "Fasciola hepatica",
        "genus": "Fasciola",
        "species": "hepatica",
        "stage": "adult2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Fasciola hepatica egg.jpg",
        "filepath": "pictures/Fasciola hepatica egg.jpg",
        "parasiteName": "Fasciola hepatica",
        "genus": "Fasciola",
        "species": "hepatica",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Fasciola hepatica egg2.jpg",
        "filepath": "pictures/Fasciola hepatica egg2.jpg",
        "parasiteName": "Fasciola hepatica",
        "genus": "Fasciola",
        "species": "hepatica",
        "stage": "egg2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Fasciolopsis buski adult.jpg",
        "filepath": "pictures/Fasciolopsis buski adult.jpg",
        "parasiteName": "Fasciolopsis buski",
        "genus": "Fasciolopsis",
        "species": "buski",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Fasciolopsis buski adult2.jpg",
        "filepath": "pictures/Fasciolopsis buski adult2.jpg",
        "parasiteName": "Fasciolopsis buski",
        "genus": "Fasciolopsis",
        "species": "buski",
        "stage": "adult2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Fasciolopsis buski egg.jpg",
        "filepath": "pictures/Fasciolopsis buski egg.jpg",
        "parasiteName": "Fasciolopsis buski",
        "genus": "Fasciolopsis",
        "species": "buski",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Fasciolopsis buski egg2.jpg",
        "filepath": "pictures/Fasciolopsis buski egg2.jpg",
        "parasiteName": "Fasciolopsis buski",
        "genus": "Fasciolopsis",
        "species": "buski",
        "stage": "egg2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Giardia lamblia 2.jpg",
        "filepath": "pictures/Giardia lamblia 2.jpg",
        "parasiteName": "Giardia lamblia",
        "genus": "Giardia",
        "species": "lamblia",
        "stage": "2",
        "stageClean": "2",
        "isLifecycle": false
    },
    {
        "filename": "Giardia lamblia life cycle.jpg",
        "filepath": "pictures/Giardia lamblia life cycle.jpg",
        "parasiteName": "Giardia lamblia",
        "genus": "Giardia",
        "species": "lamblia",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Giardia lamblia.jpg",
        "filepath": "pictures/Giardia lamblia.jpg",
        "parasiteName": "Giardia lamblia",
        "genus": "Giardia",
        "species": "lamblia",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Heterophyes heterophyes adult 2.jpg",
        "filepath": "pictures/Heterophyes heterophyes adult 2.jpg",
        "parasiteName": "Heterophyes heterophyes",
        "genus": "Heterophyes",
        "species": "heterophyes",
        "stage": "adult 2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Heterophyes heterophyes adult 3.jpg",
        "filepath": "pictures/Heterophyes heterophyes adult 3.jpg",
        "parasiteName": "Heterophyes heterophyes",
        "genus": "Heterophyes",
        "species": "heterophyes",
        "stage": "adult 3",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Heterophyes heterophyes adult.jpg",
        "filepath": "pictures/Heterophyes heterophyes adult.jpg",
        "parasiteName": "Heterophyes heterophyes",
        "genus": "Heterophyes",
        "species": "heterophyes",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Heterophyes heterophyes egg.jpg",
        "filepath": "pictures/Heterophyes heterophyes egg.jpg",
        "parasiteName": "Heterophyes heterophyes",
        "genus": "Heterophyes",
        "species": "heterophyes",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "hookwarm life cycle.jpg",
        "filepath": "pictures/hookwarm life cycle.jpg",
        "parasiteName": "hookwarm life",
        "genus": "hookwarm",
        "species": "life",
        "stage": "cycle",
        "stageClean": "cycle",
        "isLifecycle": false
    },
    {
        "filename": "Hymenolepis diminuta egg 2.jpg",
        "filepath": "pictures/Hymenolepis diminuta egg 2.jpg",
        "parasiteName": "Hymenolepis diminuta",
        "genus": "Hymenolepis",
        "species": "diminuta",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Hymenolepis diminuta egg.jpg",
        "filepath": "pictures/Hymenolepis diminuta egg.jpg",
        "parasiteName": "Hymenolepis diminuta",
        "genus": "Hymenolepis",
        "species": "diminuta",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Hymenolepis diminuta.jpg",
        "filepath": "pictures/Hymenolepis diminuta.jpg",
        "parasiteName": "Hymenolepis diminuta",
        "genus": "Hymenolepis",
        "species": "diminuta",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Hymenolepis nana adult.jpg",
        "filepath": "pictures/Hymenolepis nana adult.jpg",
        "parasiteName": "Hymenolepis nana",
        "genus": "Hymenolepis",
        "species": "nana",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Hymenolepis nana body.jpg",
        "filepath": "pictures/Hymenolepis nana body.jpg",
        "parasiteName": "Hymenolepis nana",
        "genus": "Hymenolepis",
        "species": "nana",
        "stage": "body",
        "stageClean": "body",
        "isLifecycle": false
    },
    {
        "filename": "Hymenolepis nana egg 2.jpg",
        "filepath": "pictures/Hymenolepis nana egg 2.jpg",
        "parasiteName": "Hymenolepis nana",
        "genus": "Hymenolepis",
        "species": "nana",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Hymenolepis nana egg.jpg",
        "filepath": "pictures/Hymenolepis nana egg.jpg",
        "parasiteName": "Hymenolepis nana",
        "genus": "Hymenolepis",
        "species": "nana",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Leishmania donovani Amastigotes.jpg",
        "filepath": "pictures/Leishmania donovani Amastigotes.jpg",
        "parasiteName": "Leishmania donovani",
        "genus": "Leishmania",
        "species": "donovani",
        "stage": "Amastigotes",
        "stageClean": "Amastigotes",
        "isLifecycle": false
    },
    {
        "filename": "Leishmania donovani life cycle.jpg",
        "filepath": "pictures/Leishmania donovani life cycle.jpg",
        "parasiteName": "Leishmania donovani",
        "genus": "Leishmania",
        "species": "donovani",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Leishmania donovani Promastigotes.jpg",
        "filepath": "pictures/Leishmania donovani Promastigotes.jpg",
        "parasiteName": "Leishmania donovani",
        "genus": "Leishmania",
        "species": "donovani",
        "stage": "Promastigotes",
        "stageClean": "Promastigotes",
        "isLifecycle": false
    },
    {
        "filename": "Leishmania donovani.jpg",
        "filepath": "pictures/Leishmania donovani.jpg",
        "parasiteName": "Leishmania donovani",
        "genus": "Leishmania",
        "species": "donovani",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Metagonimus yokogawai adult.jpg",
        "filepath": "pictures/Metagonimus yokogawai adult.jpg",
        "parasiteName": "Metagonimus yokogawai",
        "genus": "Metagonimus",
        "species": "yokogawai",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Metagonimus yokogawai egg 2.jpg",
        "filepath": "pictures/Metagonimus yokogawai egg 2.jpg",
        "parasiteName": "Metagonimus yokogawai",
        "genus": "Metagonimus",
        "species": "yokogawai",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Metagonimus yokogawai egg.jpg",
        "filepath": "pictures/Metagonimus yokogawai egg.jpg",
        "parasiteName": "Metagonimus yokogawai",
        "genus": "Metagonimus",
        "species": "yokogawai",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Necator americanus adult.jpg",
        "filepath": "pictures/Necator americanus adult.jpg",
        "parasiteName": "Necator americanus",
        "genus": "Necator",
        "species": "americanus",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Opisthorchis viverrini adult.jpg",
        "filepath": "pictures/Opisthorchis viverrini adult.jpg",
        "parasiteName": "Opisthorchis viverrini",
        "genus": "Opisthorchis",
        "species": "viverrini",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Opisthorchis viverrini egg.jpg",
        "filepath": "pictures/Opisthorchis viverrini egg.jpg",
        "parasiteName": "Opisthorchis viverrini",
        "genus": "Opisthorchis",
        "species": "viverrini",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Paragonimus westermani adult.jpg",
        "filepath": "pictures/Paragonimus westermani adult.jpg",
        "parasiteName": "Paragonimus westermani",
        "genus": "Paragonimus",
        "species": "westermani",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Paragonimus westermani egg 2.jpg",
        "filepath": "pictures/Paragonimus westermani egg 2.jpg",
        "parasiteName": "Paragonimus westermani",
        "genus": "Paragonimus",
        "species": "westermani",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Paragonimus westermani egg 3.jpg",
        "filepath": "pictures/Paragonimus westermani egg 3.jpg",
        "parasiteName": "Paragonimus westermani",
        "genus": "Paragonimus",
        "species": "westermani",
        "stage": "egg 3",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Paragonimus westermani egg.jpg",
        "filepath": "pictures/Paragonimus westermani egg.jpg",
        "parasiteName": "Paragonimus westermani",
        "genus": "Paragonimus",
        "species": "westermani",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium falciparum 3.jpg",
        "filepath": "pictures/Plasmodium falciparum 3.jpg",
        "parasiteName": "Plasmodium falciparum",
        "genus": "Plasmodium",
        "species": "falciparum",
        "stage": "3",
        "stageClean": "3",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium falciparum Crescent gametocytes 2.jpg",
        "filepath": "pictures/Plasmodium falciparum Crescent gametocytes 2.jpg",
        "parasiteName": "Plasmodium falciparum",
        "genus": "Plasmodium",
        "species": "falciparum",
        "stage": "Crescent gametocytes 2",
        "stageClean": "Crescent gametocytes 2",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium falciparum Crescent gametocytes.jpg",
        "filepath": "pictures/Plasmodium falciparum Crescent gametocytes.jpg",
        "parasiteName": "Plasmodium falciparum",
        "genus": "Plasmodium",
        "species": "falciparum",
        "stage": "Crescent gametocytes",
        "stageClean": "Crescent gametocytes",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium falciparum life cycle.jpg",
        "filepath": "pictures/Plasmodium falciparum life cycle.jpg",
        "parasiteName": "Plasmodium falciparum",
        "genus": "Plasmodium",
        "species": "falciparum",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Plasmodium falciparum Schizont.jpg",
        "filepath": "pictures/Plasmodium falciparum Schizont.jpg",
        "parasiteName": "Plasmodium falciparum",
        "genus": "Plasmodium",
        "species": "falciparum",
        "stage": "Schizont",
        "stageClean": "Schizont",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium malariae band.jpg",
        "filepath": "pictures/Plasmodium malariae band.jpg",
        "parasiteName": "Plasmodium malariae",
        "genus": "Plasmodium",
        "species": "malariae",
        "stage": "band",
        "stageClean": "band",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium malariae Gametocyte.jpg",
        "filepath": "pictures/Plasmodium malariae Gametocyte.jpg",
        "parasiteName": "Plasmodium malariae",
        "genus": "Plasmodium",
        "species": "malariae",
        "stage": "Gametocyte",
        "stageClean": "Gametocyte",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium malariae ring.jpg",
        "filepath": "pictures/Plasmodium malariae ring.jpg",
        "parasiteName": "Plasmodium malariae",
        "genus": "Plasmodium",
        "species": "malariae",
        "stage": "ring",
        "stageClean": "ring",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium malariae Rosette.jpg",
        "filepath": "pictures/Plasmodium malariae Rosette.jpg",
        "parasiteName": "Plasmodium malariae",
        "genus": "Plasmodium",
        "species": "malariae",
        "stage": "Rosette",
        "stageClean": "Rosette",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium malariae.jpg",
        "filepath": "pictures/Plasmodium malariae.jpg",
        "parasiteName": "Plasmodium malariae",
        "genus": "Plasmodium",
        "species": "malariae",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium ovale Fimbriation.jpg",
        "filepath": "pictures/Plasmodium ovale Fimbriation.jpg",
        "parasiteName": "Plasmodium ovale",
        "genus": "Plasmodium",
        "species": "ovale",
        "stage": "Fimbriation",
        "stageClean": "Fimbriation",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium ovale Macrogametocyte.jpg",
        "filepath": "pictures/Plasmodium ovale Macrogametocyte.jpg",
        "parasiteName": "Plasmodium ovale",
        "genus": "Plasmodium",
        "species": "ovale",
        "stage": "Macrogametocyte",
        "stageClean": "Macrogametocyte",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium ovale ring.jpg",
        "filepath": "pictures/Plasmodium ovale ring.jpg",
        "parasiteName": "Plasmodium ovale",
        "genus": "Plasmodium",
        "species": "ovale",
        "stage": "ring",
        "stageClean": "ring",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium ovale Schizont.jpg",
        "filepath": "pictures/Plasmodium ovale Schizont.jpg",
        "parasiteName": "Plasmodium ovale",
        "genus": "Plasmodium",
        "species": "ovale",
        "stage": "Schizont",
        "stageClean": "Schizont",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium ovale.jpg",
        "filepath": "pictures/Plasmodium ovale.jpg",
        "parasiteName": "Plasmodium ovale",
        "genus": "Plasmodium",
        "species": "ovale",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium vivax  gametocyte.jpg",
        "filepath": "pictures/Plasmodium vivax  gametocyte.jpg",
        "parasiteName": "Plasmodium vivax",
        "genus": "Plasmodium",
        "species": "vivax",
        "stage": "gametocyte",
        "stageClean": "gametocyte",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium vivax Ookinete.jpg",
        "filepath": "pictures/Plasmodium vivax Ookinete.jpg",
        "parasiteName": "Plasmodium vivax",
        "genus": "Plasmodium",
        "species": "vivax",
        "stage": "Ookinete",
        "stageClean": "Ookinete",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium vivax ring.jpg",
        "filepath": "pictures/Plasmodium vivax ring.jpg",
        "parasiteName": "Plasmodium vivax",
        "genus": "Plasmodium",
        "species": "vivax",
        "stage": "ring",
        "stageClean": "ring",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium vivax Schizont.jpg",
        "filepath": "pictures/Plasmodium vivax Schizont.jpg",
        "parasiteName": "Plasmodium vivax",
        "genus": "Plasmodium",
        "species": "vivax",
        "stage": "Schizont",
        "stageClean": "Schizont",
        "isLifecycle": false
    },
    {
        "filename": "Plasmodium vivax trophozoite.jpg",
        "filepath": "pictures/Plasmodium vivax trophozoite.jpg",
        "parasiteName": "Plasmodium vivax",
        "genus": "Plasmodium",
        "species": "vivax",
        "stage": "trophozoite",
        "stageClean": "Trophozoite (滋養體)",
        "isLifecycle": false
    },
    {
        "filename": "Raillietina celebensis adult 2.jpg",
        "filepath": "pictures/Raillietina celebensis adult 2.jpg",
        "parasiteName": "Raillietina celebensis",
        "genus": "Raillietina",
        "species": "celebensis",
        "stage": "adult 2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Raillietina celebensis adult.jpg",
        "filepath": "pictures/Raillietina celebensis adult.jpg",
        "parasiteName": "Raillietina celebensis",
        "genus": "Raillietina",
        "species": "celebensis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Raillietina celebensis egg.jpg",
        "filepath": "pictures/Raillietina celebensis egg.jpg",
        "parasiteName": "Raillietina celebensis",
        "genus": "Raillietina",
        "species": "celebensis",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma haematobium adult.jpg",
        "filepath": "pictures/Schistosoma haematobium adult.jpg",
        "parasiteName": "Schistosoma haematobium",
        "genus": "Schistosoma",
        "species": "haematobium",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma haematobium egg.jpg",
        "filepath": "pictures/Schistosoma haematobium egg.jpg",
        "parasiteName": "Schistosoma haematobium",
        "genus": "Schistosoma",
        "species": "haematobium",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma haematobium egg2.jpg",
        "filepath": "pictures/Schistosoma haematobium egg2.jpg",
        "parasiteName": "Schistosoma haematobium",
        "genus": "Schistosoma",
        "species": "haematobium",
        "stage": "egg2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma haematobium egg3.jpg",
        "filepath": "pictures/Schistosoma haematobium egg3.jpg",
        "parasiteName": "Schistosoma haematobium",
        "genus": "Schistosoma",
        "species": "haematobium",
        "stage": "egg3",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma intercalatum adult.jpg",
        "filepath": "pictures/Schistosoma intercalatum adult.jpg",
        "parasiteName": "Schistosoma intercalatum",
        "genus": "Schistosoma",
        "species": "intercalatum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma intercalatum egg.jpg",
        "filepath": "pictures/Schistosoma intercalatum egg.jpg",
        "parasiteName": "Schistosoma intercalatum",
        "genus": "Schistosoma",
        "species": "intercalatum",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma japonicum adult.jpg",
        "filepath": "pictures/Schistosoma japonicum adult.jpg",
        "parasiteName": "Schistosoma japonicum",
        "genus": "Schistosoma",
        "species": "japonicum",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma japonicum egg 2.jpg",
        "filepath": "pictures/Schistosoma japonicum egg 2.jpg",
        "parasiteName": "Schistosoma japonicum",
        "genus": "Schistosoma",
        "species": "japonicum",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma japonicum egg 3.jpg",
        "filepath": "pictures/Schistosoma japonicum egg 3.jpg",
        "parasiteName": "Schistosoma japonicum",
        "genus": "Schistosoma",
        "species": "japonicum",
        "stage": "egg 3",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma japonicum egg 4.jpg",
        "filepath": "pictures/Schistosoma japonicum egg 4.jpg",
        "parasiteName": "Schistosoma japonicum",
        "genus": "Schistosoma",
        "species": "japonicum",
        "stage": "egg 4",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma japonicum egg.jpg",
        "filepath": "pictures/Schistosoma japonicum egg.jpg",
        "parasiteName": "Schistosoma japonicum",
        "genus": "Schistosoma",
        "species": "japonicum",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma mansoni adult.jpg",
        "filepath": "pictures/Schistosoma mansoni adult.jpg",
        "parasiteName": "Schistosoma mansoni",
        "genus": "Schistosoma",
        "species": "mansoni",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma mansoni egg.jpg",
        "filepath": "pictures/Schistosoma mansoni egg.jpg",
        "parasiteName": "Schistosoma mansoni",
        "genus": "Schistosoma",
        "species": "mansoni",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma mansoni egg2.jpg",
        "filepath": "pictures/Schistosoma mansoni egg2.jpg",
        "parasiteName": "Schistosoma mansoni",
        "genus": "Schistosoma",
        "species": "mansoni",
        "stage": "egg2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Schistosoma mansoni egg3.jpg",
        "filepath": "pictures/Schistosoma mansoni egg3.jpg",
        "parasiteName": "Schistosoma mansoni",
        "genus": "Schistosoma",
        "species": "mansoni",
        "stage": "egg3",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Spirometra mansoni adult.jpg",
        "filepath": "pictures/Spirometra mansoni adult.jpg",
        "parasiteName": "Spirometra mansoni",
        "genus": "Spirometra",
        "species": "mansoni",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Spirometra mansoni egg 2.jpg",
        "filepath": "pictures/Spirometra mansoni egg 2.jpg",
        "parasiteName": "Spirometra mansoni",
        "genus": "Spirometra",
        "species": "mansoni",
        "stage": "egg 2",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Spirometra mansoni egg.jpg",
        "filepath": "pictures/Spirometra mansoni egg.jpg",
        "parasiteName": "Spirometra mansoni",
        "genus": "Spirometra",
        "species": "mansoni",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Spirometra mansoni Sparganum.jpg",
        "filepath": "pictures/Spirometra mansoni Sparganum.jpg",
        "parasiteName": "Spirometra mansoni",
        "genus": "Spirometra",
        "species": "mansoni",
        "stage": "Sparganum",
        "stageClean": "Sparganum",
        "isLifecycle": false
    },
    {
        "filename": "Strongyloides stercoralis adult.jpg",
        "filepath": "pictures/Strongyloides stercoralis adult.jpg",
        "parasiteName": "Strongyloides stercoralis",
        "genus": "Strongyloides",
        "species": "stercoralis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Strongyloides stercoralis egg.jpg",
        "filepath": "pictures/Strongyloides stercoralis egg.jpg",
        "parasiteName": "Strongyloides stercoralis",
        "genus": "Strongyloides",
        "species": "stercoralis",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Strongyloides stercoralis life cycle.jpg",
        "filepath": "pictures/Strongyloides stercoralis life cycle.jpg",
        "parasiteName": "Strongyloides stercoralis",
        "genus": "Strongyloides",
        "species": "stercoralis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Taenia saginata adult.jpg",
        "filepath": "pictures/Taenia saginata adult.jpg",
        "parasiteName": "Taenia saginata",
        "genus": "Taenia",
        "species": "saginata",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Taenia saginata body.jpg",
        "filepath": "pictures/Taenia saginata body.jpg",
        "parasiteName": "Taenia saginata",
        "genus": "Taenia",
        "species": "saginata",
        "stage": "body",
        "stageClean": "body",
        "isLifecycle": false
    },
    {
        "filename": "Taenia solium adult 2.jpg",
        "filepath": "pictures/Taenia solium adult 2.jpg",
        "parasiteName": "Taenia solium",
        "genus": "Taenia",
        "species": "solium",
        "stage": "adult 2",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Taenia solium adult.jpg",
        "filepath": "pictures/Taenia solium adult.jpg",
        "parasiteName": "Taenia solium",
        "genus": "Taenia",
        "species": "solium",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Taenia solium egg.jpg",
        "filepath": "pictures/Taenia solium egg.jpg",
        "parasiteName": "Taenia solium",
        "genus": "Taenia",
        "species": "solium",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Taenia solium larva.jpg",
        "filepath": "pictures/Taenia solium larva.jpg",
        "parasiteName": "Taenia solium",
        "genus": "Taenia",
        "species": "solium",
        "stage": "larva",
        "stageClean": "Larva/Microfilaria (幼蟲/微絲蚴)",
        "isLifecycle": false
    },
    {
        "filename": "Toxoplasma gondii 2.jpg",
        "filepath": "pictures/Toxoplasma gondii 2.jpg",
        "parasiteName": "Toxoplasma gondii",
        "genus": "Toxoplasma",
        "species": "gondii",
        "stage": "2",
        "stageClean": "2",
        "isLifecycle": false
    },
    {
        "filename": "Toxoplasma gondii 3.jpg",
        "filepath": "pictures/Toxoplasma gondii 3.jpg",
        "parasiteName": "Toxoplasma gondii",
        "genus": "Toxoplasma",
        "species": "gondii",
        "stage": "3",
        "stageClean": "3",
        "isLifecycle": false
    },
    {
        "filename": "Toxoplasma gondii life cycle.jpg",
        "filepath": "pictures/Toxoplasma gondii life cycle.jpg",
        "parasiteName": "Toxoplasma gondii",
        "genus": "Toxoplasma",
        "species": "gondii",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Toxoplasma gondii.jpg",
        "filepath": "pictures/Toxoplasma gondii.jpg",
        "parasiteName": "Toxoplasma gondii",
        "genus": "Toxoplasma",
        "species": "gondii",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Trichinella spiralis adult.jpg",
        "filepath": "pictures/Trichinella spiralis adult.jpg",
        "parasiteName": "Trichinella spiralis",
        "genus": "Trichinella",
        "species": "spiralis",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Trichinella spiralis ENCYSTED LARVAE.jpg",
        "filepath": "pictures/Trichinella spiralis ENCYSTED LARVAE.jpg",
        "parasiteName": "Trichinella spiralis",
        "genus": "Trichinella",
        "species": "spiralis",
        "stage": "ENCYSTED LARVAE",
        "stageClean": "Larva/Microfilaria (幼蟲/微絲蚴)",
        "isLifecycle": false
    },
    {
        "filename": "Trichinella spiralis life cycle.jpg",
        "filepath": "pictures/Trichinella spiralis life cycle.jpg",
        "parasiteName": "Trichinella spiralis",
        "genus": "Trichinella",
        "species": "spiralis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Trichomonas vaginalis 2.jpg",
        "filepath": "pictures/Trichomonas vaginalis 2.jpg",
        "parasiteName": "Trichomonas vaginalis",
        "genus": "Trichomonas",
        "species": "vaginalis",
        "stage": "2",
        "stageClean": "2",
        "isLifecycle": false
    },
    {
        "filename": "Trichomonas vaginalis life cycle.jpg",
        "filepath": "pictures/Trichomonas vaginalis life cycle.jpg",
        "parasiteName": "Trichomonas vaginalis",
        "genus": "Trichomonas",
        "species": "vaginalis",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Trichomonas vaginalis.jpg",
        "filepath": "pictures/Trichomonas vaginalis.jpg",
        "parasiteName": "Trichomonas vaginalis",
        "genus": "Trichomonas",
        "species": "vaginalis",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    },
    {
        "filename": "Trichuris trichiura adult.jpg",
        "filepath": "pictures/Trichuris trichiura adult.jpg",
        "parasiteName": "Trichuris trichiura",
        "genus": "Trichuris",
        "species": "trichiura",
        "stage": "adult",
        "stageClean": "Adult (成蟲)",
        "isLifecycle": false
    },
    {
        "filename": "Trichuris trichiura egg.jpg",
        "filepath": "pictures/Trichuris trichiura egg.jpg",
        "parasiteName": "Trichuris trichiura",
        "genus": "Trichuris",
        "species": "trichiura",
        "stage": "egg",
        "stageClean": "Egg (卵)",
        "isLifecycle": false
    },
    {
        "filename": "Trichuris trichiura life cycle.jpg",
        "filepath": "pictures/Trichuris trichiura life cycle.jpg",
        "parasiteName": "Trichuris trichiura",
        "genus": "Trichuris",
        "species": "trichiura",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Trypanosoma cruzi 2.jpg",
        "filepath": "pictures/Trypanosoma cruzi 2.jpg",
        "parasiteName": "Trypanosoma cruzi",
        "genus": "Trypanosoma",
        "species": "cruzi",
        "stage": "2",
        "stageClean": "2",
        "isLifecycle": false
    },
    {
        "filename": "Trypanosoma cruzi 3.jpg",
        "filepath": "pictures/Trypanosoma cruzi 3.jpg",
        "parasiteName": "Trypanosoma cruzi",
        "genus": "Trypanosoma",
        "species": "cruzi",
        "stage": "3",
        "stageClean": "3",
        "isLifecycle": false
    },
    {
        "filename": "Trypanosoma cruzi life cycle.jpg",
        "filepath": "pictures/Trypanosoma cruzi life cycle.jpg",
        "parasiteName": "Trypanosoma cruzi",
        "genus": "Trypanosoma",
        "species": "cruzi",
        "stage": "life cycle",
        "stageClean": "Life Cycle (生活史教學)",
        "isLifecycle": true
    },
    {
        "filename": "Trypanosoma cruzi.jpg",
        "filepath": "pictures/Trypanosoma cruzi.jpg",
        "parasiteName": "Trypanosoma cruzi",
        "genus": "Trypanosoma",
        "species": "cruzi",
        "stage": "Unknown",
        "stageClean": "Unknown",
        "isLifecycle": false
    }
];
