import os
import json
import re

def main():
    pic_dir = r"c:\Users\tlcha\Documents\parasite poker\pictures"
    files = os.listdir(pic_dir)
    
    db = []
    for f in files:
        if f.lower().endswith(('.jpg', '.jpeg', '.png', '.gif')):
            # 檔名，例如: "Ancylostoma caninum adult.jpg"
            name_without_ext = os.path.splitext(f)[0]
            
            # 拆分字詞
            # 有些是用空格，有些是底線，我們都支援
            parts = re.split(r'[\s_]+', name_without_ext)
            if len(parts) >= 2:
                genus = parts[0]
                species = parts[1]
                parasite_name = f"{genus} {species}"
                
                # 剩餘的部分是型態 (e.g. "adult 2", "egg", "life cycle")
                stage_parts = parts[2:]
                stage = " ".join(stage_parts) if stage_parts else "Unknown"
                
                is_lifecycle = "life cycle" in stage.lower() or "lifecycle" in stage.lower() or "life_cycle" in stage.lower()
                
                # 乾淨的階段名稱，比如 "Egg", "Adult", "Larva", "Cyst" 等
                stage_clean = stage
                if "egg" in stage.lower():
                    stage_clean = "Egg (卵)"
                elif "adult" in stage.lower():
                    stage_clean = "Adult (成蟲)"
                elif "larva" in stage.lower() or "larvae" in stage.lower() or "microfilaria" in stage.lower() or "l3" in stage.lower():
                    stage_clean = "Larva/Microfilaria (幼蟲/微絲蚴)"
                elif "cyst" in stage.lower():
                    stage_clean = "Cyst (包囊)"
                elif "trophozoite" in stage.lower():
                    stage_clean = "Trophozoite (滋養體)"
                elif "life cycle" in stage.lower():
                    stage_clean = "Life Cycle (生活史教學)"
                
                db.append({
                    "filename": f,
                    "filepath": f"pictures/{f}",
                    "parasiteName": parasite_name,
                    "genus": genus,
                    "species": species,
                    "stage": stage,
                    "stageClean": stage_clean,
                    "isLifecycle": is_lifecycle
                })
            else:
                # 處理不符 Genus species 的特殊檔名 (如 hookwarm life cycle.jpg)
                db.append({
                    "filename": f,
                    "filepath": f"pictures/{f}",
                    "parasiteName": "Hookworm",
                    "genus": "Hookworm",
                    "species": "spp.",
                    "stage": name_without_ext,
                    "stageClean": "Life Cycle (生活史教學)",
                    "isLifecycle": True
                })
                
    # 輸出為 JS 檔案
    output_js = os.path.join(r"c:\Users\tlcha\Documents\parasite poker", "images_db.js")
    with open(output_js, "w", encoding="utf-8") as out:
        out.write("/* Automatically generated by parse_images.py */\n")
        out.write("const PARASITE_IMAGES = ")
        json.dump(db, out, ensure_ascii=False, indent=4)
        out.write(";\n")
        
    print(f"Successfully parsed {len(db)} images and generated images_db.js")

if __name__ == "__main__":
    main()
